### ISSUE TITLE
please add support for www.wlnupdates.com

### ISSUE THREAD

**Issue by Emasoft** [kcfang2215/novel-alerts#7]
Can you add support for www.wlnupdates.com? It is much more frequently updated than www.novelupdates.com.

**Comment by Kevin-C-Fang** [comment]
Yes, I can. I'll comment on this when it's finished. How did you find this repo?

**Comment by Kevin-C-Fang** [comment]
Added the web scrape function for wlnupdates.com. I will add a new release after this.
